#!/bin/bash

echo "$1" | sed "s/^roi_y:.*/roi_y:1/" | sed "s/^pipeline_res:.*/pipeline_res:2/" | sed "s/^roi_x:.*/roi_x:0/" >zoomInPanHigh.vpr
echo "$1" | sed "s/^roi_y:.*/roi_y:-1/" | sed "s/^pipeline_res:.*/pipeline_res:2/" | sed "s/^roi_x:.*/roi_x:0/" >zoomInPanLow.vpr
echo "$1" | sed "s/^roi_y:.*/roi_y:0/" | sed "s/^pipeline_res:.*/pipeline_res:2/" | sed "s/^roi_x:.*/roi_x:0/" >zoomInPanMid.vpr
