#!/bin/bash

cat "$1" | sed "s/^roi_y:.*/roi_y:1/" | sed "s/^pipeline_res:.*/pipeline_res:2/" | sed "s/^roi_x:.*/roi_x:0/" > zoomInPanHigh.vpr
cat "$1" | sed "s/^roi_y:.*/roi_y:-1/" | sed "s/^pipeline_res:.*/pipeline_res:2/" | sed "s/^roi_x:.*/roi_x:0/" > zoomInPanLow.vpr
cat "$1" | sed "s/^roi_y:.*/roi_y:0/" | sed "s/^pipeline_res:.*/pipeline_res:2/" | sed "s/^roi_x:.*/roi_x:0/"> zoomInPanMid.vpr
