language: java

install:
  - pip install --user codecov
script:
  - travis_wait 30 ./gradlew clean :simulated:build :twenty:build
after_success:
  - codecov -t 934fa7e1-6db9-4724-9e86-84736fdb299a

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/