language: kotlin
sudo: false
before_install:
  - pip install --user codecov
script:
  - ./gradlew clean :simulated:check :nineteen:build
after_success:
  - codecov -t 934fa7e1-6db9-4724-9e86-84736fdb299a
cache:
  directories:
    - $HOME/.gradle